### PR TITLE
fix : Fixing Flight A detection when having jump boost

### PR DESCRIPTION
**Pull request by DreaMzyGit**

### CODE REVIEW

**Comment by DreaMzyGit** [comment]
FastPlace Fix : Tested on a factions server, a player builds sand walls while being in a minecart and keeping the right click pressed creating false positives with the check.

Flight A Fix : Like Flight B, Flight A must take into account the jumpboost effect. When a player takes velocity (for example when a custom monster sends him into the air with an attack) the check does not take into account this velocity. Also, when a player is teleported back like in "safezone" it is consigned as in flight.

Motion D : A player moving at high speed in a boat makes false positives. 

Interact B : When a player places blocks (use bug blocks) in a region where the BlockPlaceEvent is cancelled the player is considered to be in fly. It really flies for the server (2/3 blocks high) but it overloads with reports for an action very often performed by players (especially in factions).

OmniSprint : False positives when a player is moving diagonally in liquid ? Should we really check the speedhack in the water?

I have disabled a lot of detections that are not essential in my situation (Jesus, badpackets, fastclimb, inventory, and more...) because we are using a modified client and a custom spigot. I am doing this pull request only on the "types of detections" that I have had the opportunity to test. I use several of your detections in my personal anti-cheat. 

These detections are tested on a network with +1000 players connected simultaneously. 

Good luck!

**Comment by Tecnio** [comment]
Thanks for testing it on a real server and sharing your issues as well as fixing them for me, I greatly appreciate this and I give my thanks!

**Comment by Tecnio** [comment]
Thank you for disabling checks that might false flag with a custom client many thanks. I hope more people like you come to this community.

**Comment by DreaMzyGit** [comment]
No problem, you do a good job, it's the least you can do to participate when you use someone else's work!

**Pull request merged**
